### ISSUE TITLE
Network crash

### ISSUE THREAD

**Issue by helio58** [ska-la/4VLC#1]
Hi trying to use your repository,
Looks great.
I can't make it work.
When i press play the network crashes. Try in windows and Mac.
Is there a setting I m missing?
Thanks

**Comment by ska-la** [comment]
hello. Congratulation! Since it was posted, you're first who ask question. Thanks.
i tested the config: win7 as server VLC and Linux or Android device as client or RC - it worked. Problem can arise when server and client (both VLC) operate on a same comp. A main problem to use a multicast streaming is a home router disables the stream by default. Not any router provides web interface to tune the option. My former router TP-Link didn't transfer a multicast traffic from LAN to WLAN and had only IPTV enable option for WAN interface. I replaced it with ASUS RT-N16 which has a more flexible interface. Can you provide your network config more precisely and what do you mean "network crashes" ?

**Comment by helio58** [comment]
Tank you for answering and for your work.

I have started vlc with lua and web interface on windows7
With a iPhone went to vlc/4vlc page.
Choose a mp4 file press play
Nothing happen the windows 7 computer cannot connect to network.
All other computers on lan cannot connect to internet.
I m using a asus router AC66.
I maybe missed same setting i the router part?
Or maybe I m using your app the wrong way.
Once again thanks

________________________________
Från: Suchkov K.A. <notifications@github.com>
Skickat: den 29 oktober 2017 19:56
Till: ska-la/4VLC
Kopia: Jose; Author
Ämne: Re: [ska-la/4VLC] Network crash (#1)


hello. Congratulation! Since it was posted, you're first who ask question. Thanks.
i tested the config: win7 as server VLC and Linux or Android device as client or RC - it worked. Problem can arise when server and client (both VLC) operate on a same comp. A main problem to use a multicast streaming is a home router disables the stream by default. Not any router provides web interface to tune the option. My former router TP-Link didn't transfer a multicast traffic from LAN to WLAN and had only IPTV enable option for WAN interface. I replaced it with ASUS RT-N16 which has a more flexible interface. Can you provide your network config more precisely and what do you mean "network crashes" ?

**Comment by ska-la** [comment]
i have not win7 comp near (i don't use Wins at all).. your win7 VLC server must be connected to router via ethernet or wifi will be overloaded. if your other computers connect to internet via wifi also, they will have narrow bandwidth and looks like lost connection.
Before press Play (and further during playback) you can verify VLM's state. On win7 go to Tools -> VLM Config (Ctrl+W), look at details [here](https://wiki.videolan.org/Documentation:Interface/)
Even if win7 looks like lost connection, it's possibly (and it's more likely) it broadcasts your Task. it's presumed that win7 uses wifi connection.
i didn't use vlm's interface on win7 but you can try: del Task (details [here](https://wiki.videolan.org/Documentation:Streaming_HowTo/VLM/)). After that your wifi network must operates as before.
Good luck..

**Comment by helio58** [comment]
Thanks,
Now I see what I was doing wrong. Using wifi.
Thank you
